name: Deploy to Azure VM

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up SSH with password authentication
        run: |
          sudo apt-get install -y sshpass

      - name: Deploy to Azure VM
        run: |
          sshpass -p "${{ secrets.AZURE_SSH_PASSWORD }}" ssh -o StrictHostKeyChecking=no ${{ secrets.AZURE_SSH_USER }}@${{ secrets.AZURE_VM_IP }} << 'EOF'
          
            echo "== Environment Info =="
            whoami
            pwd
            date
            echo "PATH: $PATH"
            which git
            which docker
      
            echo "== Fixing ownership on project folder =="
            sudo chown -R $USER:$USER ~/projects/bolt.newer
      
            echo "== Allowing project directory for Git =="
            git config --global --add safe.directory /home/${USER}/projects/bolt.newer
      
            echo "== Navigating to project =="
            cd ~/projects/bolt.newer || { echo "Project folder missing!"; exit 1; }
      
            echo "== Checking out main branch =="
            git checkout main || { echo "Failed to checkout main"; exit 1; }
      
            echo "== Pulling latest changes =="
            git pull --no-rebase || { echo "Git pull failed"; exit 1; }
      
            echo "== Navigating to backend =="
            cd be || { echo "'be' directory not found!"; exit 1; }
      
            echo "== Building Docker image =="
            sudo docker build -t bn-api . || { echo "Docker build failed"; exit 1; }
      
            echo "== Stopping and removing old container (if any) =="
            sudo docker stop bn-api || true
            sudo docker rm bn-api || true
      
            echo "== Running new container =="
            sudo docker run -d -p 5001:5001 --name bn-api --env-file .env bn-api || { echo "Docker run failed"; exit 1
            echo "== Deployment Complete =="
          EOF

