name: Deploy to Azure VM

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up SSH with password authentication
        run: |
          sudo apt-get install -y sshpass

      - name: Deploy to Azure VM
        run: |
          sshpass -p "${{ secrets.AZURE_SSH_PASSWORD }}" ssh -o StrictHostKeyChecking=no ${{ secrets.AZURE_SSH_USER }}@${{ secrets.AZURE_VM_IP }} << 'EOF'

            cd ~/projects/bolt.newer
            git checkout main
            git pull origin main
            cd be

            docker build -t bn-api .
            docker stop bn-api || true
            docker rm bn-api || true

            docker run -d -p 5001:5001 --name bn-api --env-file ~/projects/bolt.newer/be/.env bn-api

            echo "Deployment complete!"
          EOF
